name: bosunski/dev

env:
  PSB_DIR: "${HOME}/.dev/`echo $PWD | md5`"

steps:
  - spc:
      combine:
        input: builds/dev.phar
        output: builds/dev
      php:
        version: 8.3
        preset: common
        extensions:
          - swoole
          - ffi
        sources: {}
  - script:
      desc: Install composer dependencies
      run: composer install

  - script:
      desc: Create output.txt
      run: echo "Hello World $(date)" > output.txt

commands:
  build:
    desc: Build DEV binary
    signature: "{name?} {subcommand?} {--service}"
    run: |
      php dev app:build --build-version=development dev.phar && \
      php dev spc:combine && chmod +x builds/dev && \
      rm builds/dev.phar
  install:
    desc: Install Dev binary
    run: |
      php dev build && \
      install builds/dev $HOME/.dev/bin/dev
  php:
    desc: PHP INI_DIR
    run: echo $PHP_DIR
  style:
    desc: Fix PHP code style
    run: pint
  analyse:
    desc: PHPStan Analyse
    run: ./vendor/bin/phpstan analyse --memory-limit=2G
  test:
    desc: Run PHP tests
    run: php vendor/bin/pest
  coverage:
    desc: Run PHP tests
    run: php -d zend_extension=$PWD/dist/xdebug.so vendor/bin/pest --coverage

serve:
  write: while true; do echo "Hello, DEV! The time is $(date)" >> output.txt; sleep 1; done
  tail: tail -f output.txt

sites:
  github: https://github.com/phpsandbox/dev
