name: dev

env:
  PSB_DIR: "${HOME}/.dev/`echo $PWD | md5`"
  PROCF: "${PWD}/Procfile"
  GITHUB_TOKEN:
    prompt: "What is your GitHub Token?"
    hint: "You can generate a token at https://github.com/settings/tokens"
    placeholder: "Looks like ghp_5geLPNwhHzgAEDHZZzR4n5ko"

steps:
  - spc:
      combine:
        input: builds/dev.phar
        output: builds/dev
      php:
        version: 8.2
        preset: common
        extensions:
          - swoole
          - ffi
        sources:
          swoole: https://github.com/swoole/swoole-src/archive/refs/heads/master.tar.gz
  - mysql:
      version: 8.0
      databases:
        - dev_development
        - dev_test
  - script:
      desc: Install composer dependencies
      run: composer install

  - script:
      desc: Create output.txt
      run: echo "Hello World $(date)" > output.txt

commands:
  build:
    desc: Build DEV binary
    signature: "{name?} {subcommand?} {--service}"
    run: |
      php dev app:build --build-version=dev dev.phar && \
      php dev spc:combine && chmod +x builds/dev && \
      rm builds/dev.phar
  install:
    desc: Install Dev binary
    run: |
      php dev build && \
      sudo install builds/dev /usr/local/bin/dev
  php:
    desc: PHP INI_DIR
    run: echo $PHP_DIR
  build-php:
    desc: Build PHP
    run: ./scripts/build-static-cli
  style:
    desc: Fix PHP code style
    run: pint
  analyse:
    desc: Check PHP version
    run: ./vendor/bin/phpstan analyse --memory-limit=2G
  test:
    desc: Run PHP tests
    run: php -d zend_extension=/opt/homebrew/lib/php/pecl/20220829/xdebug.so -d memory_limit=-1 vendor/bin/pest --coverage
  pro:
    desc: PRO
    run: echo $PSB_DIR

serve:
  write: while true; do echo "Hello, DEV! The time is $(date)" >> output.txt; sleep 1; done
  tail: tail -f output.txt

sites:
  github: https://github.com/phpsandbox/dev
