name: dev
php: 8.2.10

services:
    - crazywhalecc/static-php-cli

up:
  - script:
        name: Install composer dependencies
        run: composer install
  - script:
        name: Setup Static PHP
        met?: |
          PHP_PATH=$SOURCE_ROOT/crazywhalecc/static-php-cli/buildroot/bin/php && test -f $PHP_PATH \
          && PHP_INI_SCAN_DIR="" \
          && $PHP_PATH -r 'version_compare(phpversion(), "8.2.10", ">=") ? exit(0) : exit(1);'
        run: ./scripts/build-static-cli
  - script:
      name: Create output.txt
      met?: test -f output.txt
      run: echo "Hello World $(date)\n" > output.txt
commands:
    build-phar:
        desc: Build Dev binary
        run: box compile
    build-bin:
        desc: Build Dev binary
        run: |
          box compile && \
          cd $SOURCE_ROOT/crazywhalecc/static-php-cli && \
          $PHP_BIN -d memory_limit=-1 bin/spc micro:combine $SOURCE_ROOT/bosunski/dev/build/garm.phar -O $SOURCE_ROOT/bosunski/dev/build/garm.bin
sites:
    google: https://www.google.com
