name: dev

env:
  PSB_DIR: "${HOME}/.dev/`echo $PWD | md5`"

steps:
  - spc:
      combine:
        input: builds/dev.phar
        output: builds/dev
      php:
        version: 8.3
        preset: common
        extensions:
          - swoole
          - ffi
  - script:
      desc: Build PCOV
      run: |
        cd $DEV_PROJECT_ROOT/krakjoe/pcov && \
        phpize && \
        ./configure --enable-pcov && \
        make && \
        make test
  - script:
      desc: Install composer dependencies
      run: composer install

  - script:
      desc: Create output.txt
      run: echo "Hello World $(date)" > output.txt

commands:
  build:
    desc: Build DEV binary
    signature: "{name?} {subcommand?} {--service}"
    run: |
      php dev app:build --build-version=dev dev.phar && \
      php dev spc:combine && chmod +x builds/dev && \
      rm builds/dev.phar
  install:
    desc: Install Dev binary
    run: |
      php dev build && \
      sudo install builds/dev /usr/local/bin/dev
  php:
    desc: PHP INI_DIR
    run: echo $PHP_DIR
  build-php:
    desc: Build PHP
    run: ./scripts/build-static-cli
  style:
    desc: Fix PHP code style
    run: pint
  analyse:
    desc: PHPStan Analyse
    run: ./vendor/bin/phpstan analyse --memory-limit=2G
  test:
    desc: Run PHP tests
    run: php vendor/bin/pest
  pro:
    desc: PRO
    run: echo $PSB_DIR

serve:
  write: while true; do echo "Hello, DEV! The time is $(date)" >> output.txt; sleep 1; done
  tail: tail -f output.txt

sites:
  github: https://github.com/phpsandbox/dev
