name: dev
php: 8.2.10

services:
    - crazywhalecc/static-php-cli

up:
  - valet:
      php: 8.2
  - script:
        desc: Install composer dependencies
        run: composer install
  - script:
        desc: Setup Static PHP
        met?: |
          PHP_PATH=$SERVICE_ROOT/crazywhalecc/static-php-cli/buildroot/bin/php && test -f $PHP_PATH \
          && PHP_INI_SCAN_DIR="" \
          && $PHP_PATH -r 'version_compare(phpversion(), "8.2.10", ">=") ? exit(0) : exit(1);'
        run: ./scripts/build-static-cli
  - script:
      desc: Create output.txt
      met?: test -f output.txt
      run: echo "Hello World $(date)\n" > output.txt
commands:
    build-phar:
        desc: Build Dev binary
        run: box compile
    build-bin:
        desc: Build Dev binary
        run: |
          box compile && \
          mv dev.phar builds/dev.phar && \
          cd $SERVICE_ROOT/crazywhalecc/static-php-cli && \
          php -d memory_limit=-1 bin/spc micro:combine $SOURCE_ROOT/bosunski/dev/builds/dev.phar -O $SOURCE_ROOT/bosunski/dev/builds/dev && \
          chmod +x $SOURCE_ROOT/bosunski/dev/builds/dev && \
          rm $SOURCE_ROOT/bosunski/dev/builds/dev.phar
    install-bin:
        desc: Install
        run: sudo install builds/dev /usr/local/bin/dev
sites:
    google: https://www.google.com
