#!/usr/bin/env bash
set -e

cd "$HOME"/src/github.com/crazywhalecc/static-php-cli

bin/spc download --all --clean
bin/spc download --all --with-php=8.2
bin/spc build --build-micro --build-cli "bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,mbstring,mbregex,mysqli,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,redis,session,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,swoole,sodium,intl"
