#!/usr/bin/env bash
set -e
export EXTENSIONS="bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,iconv,mbstring,mbregex,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,sodium"

cd "$SERVICE_ROOT"/crazywhalecc/static-php-cli

composer install --no-plugins

bin/spc download --all --with-php=8.2 --for-extensions="$EXTENSIONS"
bin/spc build --build-micro --build-cli "$EXTENSIONS"
