import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { Config } from './config/config.js'
import type { Runner } from './execution/runner.js'
import type { IOInterface } from './types/io.js'
import type { PluginManager } from './plugin/plugin-manager.js'
import type { EnvProvider, PathProvider } from './types/capability.js'
import { ENV_PROVIDER, PATH_PROVIDER } from './types/capability.js'

export class Dev {
  readonly name = 'dev'
  private _pluginManager!: PluginManager
  readonly initialized: boolean

  constructor(
    public readonly config: Config,
    public readonly runner: Runner,
    private _io: IOInterface,
  ) {
    this.runner.setEnvResolver(() => this.resolveEnvs())
    this.initialized = existsSync(this.config.file())
  }

  getPluginManager(): PluginManager {
    return this._pluginManager
  }

  setPluginManager(pm: PluginManager): void {
    this._pluginManager = pm
  }

  io(): IOInterface {
    return this._io
  }

  setIO(io: IOInterface): void {
    this._io = io
  }

  async resolveEnvs(): Promise<Map<string, string>> {
    const base = await this.config.envs()

    const pluginEnvEntries = this._pluginManager
      .getPluginCapabilities<EnvProvider>(ENV_PROVIDER, { dev: this })
      .flatMap(cap => Object.entries(cap.envs()))

    const extras: [string, string][] = [
      ['DEV_PATH', this.config.devPath()],
      ['DEV', '1'],
      ['DEV_SOURCE_ROOT', Config.sourcePath()],
      ['DEV_PROJECT_ROOT', this.config.cwd()],
    ]

    return new Map([...base, ...pluginEnvEntries, ...extras])
  }

  paths(): string[] {
    // globalPath prepended first so project devPath (prepended last) wins in PATH
    const base = [this.config.globalPath('bin'), this.config.devPath('bin')]

    const pluginPaths = this._pluginManager
      .getPluginCapabilities<PathProvider>(PATH_PROVIDER, { dev: this })
      .flatMap(cap => cap.paths())

    // Deduplicate while preserving order (last occurrence wins for prepend semantics)
    const all = [...base, ...pluginPaths]
    return all.filter((p, i) => all.lastIndexOf(p) === i)
  }

  async updateEnvironment(): Promise<boolean> {
    if (!this.initShadowenvDir()) return false
    await this.primeEnvCache()
    if (this.createDefaultLispFile() && this.createGitIgnoreFile()) {
      return this.runner.withoutShadowEnv().exec([this.config.brewPath('bin/shadowenv'), 'trust'])
    }
    return false
  }

  private initShadowenvDir(): boolean {
    const dir = this.config.cwd(this.shadowenvPath())
    if (existsSync(dir)) return true
    try {
      mkdirSync(dir, { recursive: true, mode: 0o755 })
      return true
    } catch {
      return false
    }
  }

  private createDefaultLispFile(): boolean {
    try {
      writeFileSync(this.config.cwd(this.shadowenvPath('000_default.lisp')), this.defaultLispContent())
      return true
    } catch {
      return false
    }
  }

  private createGitIgnoreFile(): boolean {
    try {
      writeFileSync(this.config.cwd(this.shadowenvPath('.gitignore')), '.*\n!.gitignore\n')
      return true
    } catch {
      return false
    }
  }

  private shadowenvPath(p?: string): string {
    return p ? `.shadowenv.d/${p}` : '.shadowenv.d'
  }

  private defaultLispContent(): string {
    const paths = this.paths()
    const envs = this._envCache ? [...this._envCache] : []

    const pathLines = paths.map(p => `(env/prepend-to-pathlist "PATH" "${p}")`).join('\n')
    const envLines = envs.map(([k, v]) => `(env/set "${k}" "${v}")`).join('\n')

    return `; Generated by dev — do not edit manually\n${pathLines}\n${envLines}\n`
  }

  private _envCache: Map<string, string> | null = null

  async primeEnvCache(): Promise<void> {
    this._envCache = await this.resolveEnvs()
  }

  isDebug(): boolean {
    return this.config.isDebug()
  }

  isInitialized(): boolean {
    return existsSync(this.config.file())
  }
}
