name: CI on x86_64 macOS

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test for ${{ matrix.platform }}
    strategy:
      matrix:
        os:
          - macos-latest-xlarge
        include:
          - os: macos-latest-xlarge
            arch: arm64
            platform: macOS

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ github.repository }}-${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ github.repository }}-${{ runner.os }}-php-

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, bcmath
          tools: composer:v2
          coverage: pcov
      
      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest
        if: steps.composer-cache.outputs.cache-hit != 'true'

      - name: Check Code Styles
        run: vendor/bin/pint --test -v

      - name: Run Tests
        run: vendor/bin/pest --coverage -vv
