name: Test and Release Unstable

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test for ${{ matrix.platform }}
    strategy:
      matrix:
        os:
          - macos-latest
        include:
          - os: macos-latest
            arch: arm64
            platform: macOS

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ github.repository }}-${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ github.repository }}-${{ runner.os }}-php-

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, swoole
          tools: composer:v2
          coverage: pcov

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest
        if: steps.composer-cache.outputs.cache-hit != 'true'

      - name: Check Code Styles
        run: vendor/bin/pint --test -v

      - name: Run Tests
        run: vendor/bin/pest --coverage -v

  release:
    name: Draft an Unstable Release
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Create a Calver Tag
        id: calver
        run: echo "tag=v$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          make_latest: false
          tag_name: ${{ steps.calver.outputs.tag }}
          name: "${{ steps.calver.outputs.tag }} Unstable"
