name: Upload DEV Binary (Release Artifacts)

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: release-build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ github.ref_name }} on ${{ matrix.platform }}
    strategy:
      matrix:
        os:
          - macos-latest
        include:
          - os: macos-latest
            arch: arm64
            platform: macOS
            target: darwin-arm64
            filename: dev-darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, swoole
          tools: composer:v2

      - name: Checkout crazywhalecc/static-php-cli
        uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          path: spc

      - run: |
          brew tap box-project/box
          brew install automake gzip box
          echo "SPC_BUILD_OS=macos" >> $GITHUB_ENV
          box -v

      - name: Cache Composer Dependencies
        id: cache-composer-deps
        uses: actions/cache@v4
        with:
          path: vendor
          key: release-composer-${{ github.repository }}-${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            release-composer-${{ github.repository }}-${{ runner.os }}-php-

      - if: steps.cache-composer-deps.outputs.cache-hit != 'true'
        run: composer install --no-dev --no-suggest

      - name: Resolve Variables
        id: vars
        run: |
          PHP_VERSION=8.3
          SPC_EXTENSIONS="bcmath,calendar,ctype,curl,dba,dom,exif,session,filter,fileinfo,iconv,mbstring,mbregex,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,sodium,swoole,session"
          CACHE_KEY=$(echo "${{ runner.os }}-${{ matrix.arch}}-php-$PHP_VERSION-dependencies-$SPC_EXTENSIONS" | shasum -a 256 | awk '{print $1}')

          {
            echo "SPC_EXTENSIONS=$SPC_EXTENSIONS"
            echo "PHP_VERSION=$PHP_VERSION"
            echo "SPC_CACHE_KEY=spc-$CACHE_KEY"
            echo "FILEPATH=$GITHUB_WORKSPACE/dist/${{ matrix.filename }}"
            echo "CHECKSUMS=$GITHUB_WORKSPACE/dist/CHECKSUMS"
          } >> $GITHUB_OUTPUT

      - name: Cache SPC Downloads and Buildroot
        id: spc-cache
        uses: actions/cache@v4
        with:
          path: |
            spc/downloads
            spc/buildroot
          key: ${{ steps.vars.outputs.SPC_CACHE_KEY }}

      - name: Setup SPC
        run: composer update --no-dev --classmap-authoritative
        working-directory: spc

      - if: steps.spc-cache.outputs.cache-hit != 'true'
        run: ./bin/spc download --with-php=${{ steps.vars.outputs.PHP_VERSION }} --for-extensions=${{ steps.vars.outputs.SPC_EXTENSIONS }} --debug
        working-directory: spc

      - if: steps.spc-cache.outputs.cache-hit != 'true'
        run: ./bin/spc build --build-micro --build-cli --with-micro-fake-cli ${{ steps.vars.outputs.SPC_EXTENSIONS }}
        working-directory: spc

      - name: Build PHAR
        run: php dev app:build dev.phar --build-version=${{ github.ref_name }}

      - name: Build DEV binary for ${{ matrix.target }}
        working-directory: spc
        run: |
            php -d memory_limit=-1 bin/spc micro:combine $GITHUB_WORKSPACE/builds/dev.phar -O ${{ steps.vars.outputs.FILEPATH }}
            chmod +x ${{ steps.vars.outputs.FILEPATH }}

      - name: Zip Binary
        working-directory: ${{ github.workspace }}/dist
        run: |
          zip -r ${{ matrix.filename }}.zip ${{ matrix.filename }}

      - name: "Create Checksums"
        working-directory: ${{ github.workspace }}/dist
        run: |
          shasum -a 256 ${{ matrix.filename }}.zip > ${{ steps.vars.outputs.CHECKSUMS }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ steps.vars.outputs.FILEPATH }}.zip
            ${{ steps.vars.outputs.CHECKSUMS }}
