name: Upload DEV Binary (Release Artifacts)

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-release-artifacts:
    name: "Upload DEV Binary (Release Artifacts)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "macos-aarch64"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Reuse DEV artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: bosunski/dev
          branch: main
          workflow: build.yml
          name: "dev-${{ matrix.os }}"

      - name: "Generate Archive name"
        run: echo "filename=dev-${{ github.ref_name }}-${{ matrix.os }}.tar.gz" >> $GITHUB_ENV

      - name: "Archive Executable"
        run: tar -czf ${{ env.filename }} dev

      - name: "Create Checksums"
        run: sha256sum ${{ env.filename }} > CHECKSUMS

      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ env.filename }}
            CHECKSUMS
